import Head from 'next/head';
//import styles from '../styles/Home.module.css';
import Nav from '../components/Nav/Nav';
import Hero from '../components/Hero/Hero';
import { Routes, Route } from 'react-router-dom';

export default function Home() {
	return (
		<div className="App">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="stylesheet"
					href="https://unpkg.com/tailwindcss@2.2.19/dist/tailwind.min.css"
				/>
			</Head>

			<main>
				<Nav />
				<Hero
					title="Now built with Next.JS!"
					sub="The Serverside Rendered Framework."
					btnText="Learn More"
				/>
			</main>
		</div>
	);
}
